<script type="text/javascript">

require(
    [
        'Magento_Checkout/js/model/cart/cache',
        'Magento_Checkout/js/model/cart/totals-processor/default',
        'Magento_Checkout/js/model/quote'
    ],
    function (cartCache, totalsProcessor, quote) {
        
         setTimeout(function () {     
          cartCache.clear('cartVersion');
          totalsProcessor.estimateTotals(quote.shippingAddress());  }, 2000);
      
        
    }
);

</script>